name: Run tests
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  run-tests-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Run tests in Gradle
        run: ./gradlew clean check --info --rerun-tasks
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-report
          path: build/reports/
  run-integrationTest-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
      - name: Run tests in Gradle
        run: ./gradlew integrationTest --info --rerun-tasks
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-report
          path: build/reports/
